export { default as Contact } from "./contact/Contact"
export { default as Portfolio} from "./portfolio/Portfolio"
export { default as Home } from "./home/Home"
export { default as Resume } from "./resume/Resume"
export { default as Bio } from "./bio/Bio"