export { default as PortfolioPg } from "./portfolioPg/PortfolioPg"
export { default as HomePg } from "./homePg/HomePg"
export { default as ResumePg } from "./resumePg/ResumePg"
export { default as BioPg } from "./bioPg/BioPg"
export { default as ContactPg } from "./contactPg/ContactPg"